# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Proyectos
    url: /#projects
    weight: 10
  - name: Habilidades
    url: /#skills
    weight: 20
  - name: Experiencia
    url: /#experience
    weight: 30
  # - name: Blog
  #   url: /#blog
  #   weight: 40
  - name: Certificaciones
    url: /#certifications
    weight: 35
  - name: Contacto
    url: /#contact
    weight: 40
